### ISSUE TITLE
Can't pass all tests in product-service

### ISSUE THREAD

**Issue by ChunML** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#1]
In `ProductServiceApplicationTests.java`, the following test failed:

```
  @Test
  void getProductInvalidParameterString() {

    client.get()
      .uri("/product/no-integer")
      .accept(APPLICATION_JSON)
      .exchange()
      .expectStatus().isEqualTo(BAD_REQUEST)
      .expectHeader().contentType(APPLICATION_JSON)
      .expectBody()
        .jsonPath("$.path").isEqualTo("/product/no-integer")
        .jsonPath("$.message").isEqualTo("Type mismatch.");
  }
```

From what I've been investigating so far, the `InvalidParameterString` is not handled in the current source code. Apparently, this test will fail for all chapters. Can you have a look?

**Comment by magnus-larsson** [comment]
Hello and thanks for the question!

You are correct in that the source code doesn't handle this error. Instead, the Spring framework handles it for us!

The `productId` parameter is declared as an integer in `api/src/main/java/se/magnus/api/core/product/ProductService.java`, which is all that is required by Spring to be able to check that the value `no-integer` is bad.

You can run the test to verify that is works with the following commands:

```
git clone git@github.com:PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E.git
cd Microservices-with-Spring-Boot-and-Spring-Cloud-2E/Chapter03/2-basic-rest-services

./gradlew microservices:product-service:test --tests ProductServiceApplicationTests.getProductInvalidParameterString
```

If you want to try it out manually you can start the product service with the commands:

```
./gradlew microservices:product-service:build
java -jar microservices/product-service/build/libs/product-service-1.0.0-SNAPSHOT.jar
```

You can then, from another terminal window, try a normal request (returning HTTP status 200) with:

```
curl localhost:7001/product/1 -i
```

And, finally, make a bad request (returning HTTP status 400) with:

```
curl localhost:7001/product/no-integer -i
```

**Comment by ChunML** [comment]
Thank you for your prompt reply!

I tried to run the solution code and it did pass the test :)

However, the code that I wrote (I followed the book + the code on Github) doesn't produce the `message` field in the response in case the types mismatch. (Everything else works fine)

Anyway, I'll double check if there's any typo.

**Comment by magnus-larsson** [comment]
Ok, I see!

Maybe you missed to add the property:

```
server.error.include-message: always
```

Starting with Spring Boot v2.3, the error message is no longer displayed by default, see
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#changes-to-the-default-error-pages-content.

Hope it helps,
Magnus.

**Comment by ChunML** [comment]
Oh my gosh, that's the reason! I checked every file except those `application.yml` files.

Thanks a ton for pointing that out. Really enjoy your book so far!

**Comment by magnus-larsson** [comment]
Great, thanks, happy to hear!

Let me know if you run into more problems while working with the code examples in my book!
