### ISSUE TITLE
Typo in p.153

### ISSUE THREAD

**Issue by junh-ki** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#15]
in the page 153, it says:

"For the `product` and `review` microservices, which use MongoDB, a corresponding base class, MongoDbTestBase, has been added."

I believe this should be changed to:

"For the `product` and `recommendation` microservices, which use MongoDB, a corresponding base class, MongoDbTestBase, has been added."

**Comment by magnus-larsson** [comment]
Thanks for reporting this typo! 

I have added it to the errara section in the `README.md` file.
