### ISSUE TITLE
Incomplete hostname?

### ISSUE THREAD

**Issue by kcinyiama** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#16]
I was looking through the yaml file: https://github.com/PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E/blob/main/Chapter18/kubernetes/helm/environments/istio-system/templates/hands-on-certificate.yaml#L25 and saw that the health dns name was incomplete. Currently, its:  `health.minikube.m`

**Comment by magnus-larsson** [comment]
Oops, thanks for reporting this typo, fixed it for Chapter 18 and beyond!
