### ISSUE TITLE
Chapter 19. Centralized Logging with the EFK Stack | Error on step Initializing Kibana

### ISSUE THREAD

**Issue by webmakaka** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#19]
Hello, guys! 
Need an assistance!

When i click on "Create index Pattern", i have an error

![Screenshot from 2022-07-20 06-41-35](https://user-images.githubusercontent.com/10372159/179895541-d22ab887-d71f-4c30-a7bf-70de40a5b29d.png)

Error message:

{"statusCode":429,"error":"Too Many Requests","message":"index [.kibana_7.12.1_001] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: cluster_block_exception"}

I think the reason what there is not enough free space. 
But, how to increase space for this service? 

Thanks.

=========================

I also replaced images:

```
#image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
image: elasticsearch:7.12.1

#image: docker.elastic.co/kibana/kibana:7.12.1
image: kibana:7.12.1
```

=========================

<br/>

### Environment

```
$ cat /etc/os-release | grep 'VERSION='
VERSION="20.04.4 LTS (Focal Fossa)"
```

<br/>

```
$ java -version
java version "17.0.2" 2022-01-18 LTS
```

<br/>

```
$ docker -v
Docker version 20.10.15, build fd82621
```

I updated gradle to work with JDK17

==================================

<br/>

Minikube runs with command:

```
$ minikube start \
    --profile=handson-spring-boot-cloud \
    --memory=10240 \
    --cpus=4 \
    --disk-size=30g \
    --kubernetes-version=v1.20.5 \
    --driver=docker \
    --ports=8080:80 --ports=8443:443 \
    --ports=30080:30080 --ports=30443:30443
```

**Comment by magnus-larsson** [comment]
Hello and thanks for reporting this problem!

Can you start to check if it is Docker that is running low on disk space with the command `docker system df`?
If the command reports a lot of reclaimable space you can run the command `docker system prune --volumes`.

Hope it helps!

**Comment by webmakaka** [comment]
I removed all docker resources 

```
$ {
    docker system prune -af
    docker container prune -f
    docker image prune -f
    docker volume prune -f
    docker network prune -f
}
```

And repeated all steps from scratch. 
And I passed this step.

Thanks!
