### ISSUE TITLE
Error with code book! Help!

### ISSUE THREAD

**Issue by maosella** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#22]
Hi magnus how are you? i am getting into the world of microservices and i am a newbie in back end. I started with your ebook which I think is great and I am very happy with how it is explained, but from chapter 7 I am having problems to raise the services with docker and I can not continue my learning because I could not find a solution on the internet to the following error when I run the following command.

`cd $BOOK_HOME/Chapter07`
`./test-em-all.bash start`

Sorry for my low knowledge but I can't follow the book with this error. I tried it on my pc with windows and wsl2 and also on a macbook pro but I get the same error.

thank you very much!
![Untitled](https://user-images.githubusercontent.com/86391165/187808682-d854ebb7-7f55-4b29-b33c-24dc42d12c5d.png)

**Comment by magnus-larsson** [comment]
Hello Martin!

Great to here that you find my book useful!

Maybe you just missed to build the source code and the Docker images for this chapter?
I.e. run the commands (see p. 227): 

```
./gradlew build
docker-compose build
```

...before you start the tests with the `./test-em-all.bash start` - command.

Let me know if it helps,
Magnus.

**Comment by magnus-larsson** [comment]
Hello again Martin!

Do you need any more support regarding this issue or can I close it?

Regards,
Magnus.

**Comment by maosella** [comment]
hello magnus how are you? Sorry the last week has been an exam week for me and I didn't have time to look closely at the new error I was getting with the commands you gave me.
In fact the new commands worked, but I did not pass the persistence tests, as if they did not exist.
I reviewed the code with the corresponding persistence chapter and everything seemed to be in order.
Fortunately now I try again to take a screenshot to send it to you and everything is working. It is the first time that I successfully get everything up without getting an error. There must be some misconfiguration somewhere.
Anyway, thank you very much for your attention, I send you a screenshot so you can see that everything was raised correctly. 
I hope I can count on more of your help in case I need it while I continue studying and practicing this great book!  I hope that my simple mistakes will continue to help future novice readers!
Thank you very much, you can close the issue.
Regards from Argentina.

![Screenshot 2022-09-08 114637](https://user-images.githubusercontent.com/86391165/189154548-e1389ef9-0fd1-41f8-917f-23868abd616b.png)

**Comment by magnus-larsson** [comment]
Great, thanks! Yes, create issues as required 😄
