### ISSUE TITLE
2fa with Authorization server

### ISSUE THREAD

**Issue by slowbreathing** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#25]
Hi Magnus, 

Great book firstly.
Is there a sample code that we can rely on for 2fa on the authorization server. 

Regards

**Comment by magnus-larsson** [comment]
Hello!

No, not that I'm aware of. 
But you can checkout the Spring Auth Server project.
Here is for example a discussion on the subject: https://github.com/spring-projects/spring-authorization-server/issues/534
