### ISSUE TITLE
Chapter 16. The test cannot be passed

### ISSUE THREAD

**Issue by andreykirson** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#6]
Hello Magnus.
I ran into a problem in chapter 16, all the steps before the command "HOST=$MINIKUBE_HOST PORT=30443 USE_K8S=true ./test-em-all.bash" are running successfully, but when running the tests, 100 attempts are made to request "curl -k https://localhost:30443/actuator/health", and the test ends with the message Give up. 
Where can I see what I'm doing wrong?

**Comment by magnus-larsson** [comment]
Hello Andrey!

I suggest you run the following two commands to get an understanding of the system landscape:

1. Get the internal status of the microservices:

```
curl -k https://localhost:30443/actuator/health | jq .
```

Any component reporting DOWN needs to be inspected further, locking into its log-file with the `kubectl logs` - command is usually a good start.

2. Get the status of the microservices' pods:

```
kubectl get pods
```

Any pod reporting 0/1 instead of 1/1 needs to be inspected further, e.g. using the `kubectl logs` command.

If you can't find the root cause, please paste the output of the two commands, and I will try to assist you further!

**Comment by andreykirson** [comment]
Hello Magnus. Thank you for your prompt answer. 
Responses of the commands are below:

`kubectl wait --timeout=600s --for=condition=ready pod --all`
pod/config-server-6f4d6d4f65-hcx6g condition met
pod/mongodb-bccb55966-t8ljt condition met
pod/mysql-665d74c488-jfkvx condition met
pod/rabbitmq-6d7466d49c-4fqlf condition met
pod/zipkin-server-7bcbdf57d6-pfjqm condition met
timed out waiting for the condition on pods/auth-server-57f49648c7-9k854
timed out waiting for the condition on pods/gateway-5c7446d46b-cbs2d
timed out waiting for the condition on pods/product-784f9bc7bb-4b869
timed out waiting for the condition on pods/product-composite-6ffb8d4db8-mtl6d
timed out waiting for the condition on pods/recommendation-7468765d44-f79tf
timed out waiting for the condition on pods/review-67ccb9ffcc-5bb6r

$ kubectl get pods
![image](https://user-images.githubusercontent.com/32255911/141904204-5b769e61-b571-4e05-a672-6df95a9d7188.png)

I can't run the command `curl -k https://localhost:30443/actuator/health | jq .` cause I can't run the services. 

When I start the test by command: `HOST=$MINIKUBE_HOST PORT=30443 USE_K8S=true ./test-em-all.bash start`
recvive the follow response:

Start Tests: Tue Nov 16 07:12:09 RTZST 2021
HOST=localhost
PORT=30443
USE_K8S=true
SKIP_CB_TESTS=false
Restarting the test environment...
$ docker-compose down --remove-orphans
Removing network microsevices_multi_project_default
Network microsevices_multi_project_default not found.
$ docker-compose up -d
Creating network "microsevices_multi_project_default" with the default driver
Pulling mongodb (mongo:4.4.2)...
4.4.2: Pulling from library/mongo
Digest: sha256:02e9941ddcb949424fa4eb01f9d235da91a5b7b64feb5887eab77e1ef84a3bad
Status: Downloaded newer image for mongo:4.4.2
Pulling mysql (mysql:5.7.32)...
5.7.32: Pulling from library/mysql
Digest: sha256:e08834258fcc0efd01df358222333919df53d4a0d9b2a54da05b204b822e3b7b
Status: Downloaded newer image for mysql:5.7.32
Pulling rabbitmq (rabbitmq:3.8.11-management)...
3.8.11-management: Pulling from library/rabbitmq
Digest: sha256:abcba8d2f36f3856fac601cdefeafc1e55b2d22209afd2779567cde3667b6dc8
Status: Downloaded newer image for rabbitmq:3.8.11-management
Pulling zipkin (openzipkin/zipkin:2.23.2)...
2.23.2: Pulling from openzipkin/zipkin
Digest: sha256:1ae0572be3d26fd9ab3fd2da5e8feaa0ca0078dbc31e2ddfb881b1a56bc332b1
Status: Downloaded newer image for openzipkin/zipkin:2.23.2
Creating microsevices_multi_project_mysql_1 ...
Creating microsevices_multi_project_config-server_1 ...
Creating microsevices_multi_project_mongodb_1       ...
Creating microsevices_multi_project_rabbitmq_1      ...
Creating microsevices_multi_project_auth-server_1   ...
Creating microsevices_multi_project_config-server_1 ... error

ERROR: for microsevices_multi_project_config-server_1  Cannot create container for service config-server: invalid volume specification: 'C:\Users\79143\Documents\PetProject\microsevices_multi_project\config-repo:/config-repo:rw'
Creating microsevices_multi_project_auth-server_1   ... done
Creating microsevices_multi_project_mysql_1         ... done
Creating microsevices_multi_project_rabbitmq_1      ... done
Creating microsevices_multi_project_mongodb_1       ... done
Creating microsevices_multi_project_zipkin_1        ...
Creating microsevices_multi_project_review_1        ...
Creating microsevices_multi_project_recommendation_1 ...
Creating microsevices_multi_project_product_1        ...
Creating microsevices_multi_project_review_1         ... done
Creating microsevices_multi_project_product_1        ... done
Creating microsevices_multi_project_recommendation_1 ... done
Creating microsevices_multi_project_zipkin_1         ... done
Creating microsevices_multi_project_product-composite_1 ...
Creating microsevices_multi_project_product-composite_1 ... done

ERROR: for config-server  Cannot create container for service config-server: invalid volume specification: 'C:\Users\79143\Documents\PetProject\microsevices_multi_project\config-repo:/config-repo:rw'

ERROR: for gateway  Container "5505265ab5cc" is unhealthy.
Encountered errors while bringing up the project.

Here is  my config-repo directory structure:
![image](https://user-images.githubusercontent.com/32255911/141921721-3e6122ca-3968-406c-8b12-07b5c3778aea.png)

**Comment by andreykirson** [comment]
@magnus-larsson hello. 

I changed my OS for the project but struggled with the following problem. I've tried to fix it but can't resolve this problem.
![image](https://user-images.githubusercontent.com/32255911/142567229-3b3c5f8e-90bb-4241-986b-e229378fe961.png)

**Comment by magnus-larsson** [comment]
Great!

I think you simply missed the `&&` between the `eval $(minikube docker-env)` command and the `./gradlew build` command. That caused the "./gradlew build" command to not execute, resulting in that the "ADD" instruction in the Dockerfile fail.

**Note:** Copy/Paste from a PDF file can be tricky (e.g. newlines and space characters are not copied correctly), so be sure to doublecheck the commands as written in the PDF with the pasted commands if the commands don't work as expected-

**Comment by andreykirson** [comment]
@magnus-larsson  hello. I run correct commands but get the follow some logs of pods:

![image](https://user-images.githubusercontent.com/32255911/142745782-2b5c5553-a851-44bb-9ac5-4e2d1b5073e0.png)

![image](https://user-images.githubusercontent.com/32255911/142745824-a2af6033-3236-4346-9ae1-65328cce8769.png)

![image](https://user-images.githubusercontent.com/32255911/142745833-dd95a704-c6e5-41b8-be28-ba414434b1d3.png)

![image](https://user-images.githubusercontent.com/32255911/142745940-278935fe-a401-4b06-a77a-b615c9ea76d3.png)


![image](https://user-images.githubusercontent.com/32255911/142745852-0ac61d02-95dc-4312-9386-c16c4c7c2ad0.png)
![image](https://user-images.githubusercontent.com/32255911/142745958-db4632a8-aa6f-45e3-8d0e-e789f0fdd20c.png)

**Comment by andreykirson** [comment]
![image](https://user-images.githubusercontent.com/32255911/142746535-14741296-c446-40df-8a5c-f334c7aa8392.png)

**Comment by magnus-larsson** [comment]
From your output it seems like that the conf-server doesn't provide the configuration expected by the other microservices!
(I can see several error messages saying `can't resolve placeholder` in the log output)

Can you try the following command to see what configuration that the config-server provides for the `product` service when using the `docker` - profile (see Chapter "_12. Centralized Configuration_" for details): 

```
kubectl exec deploy/config-server -- curl dev-usr:dev-pwd@localhost:8888/product/docker -s | jq .
```

It should produce a response like the one below. If it doesn't, can you please provide the log output from the config server:

```
kubectl logs deploy/config-server
```

Expected output from the config-server:

```
{
  "name": "product",
  "profiles": [
    "docker"
  ],
  "label": null,
  "version": null,
  "state": null,
  "propertySources": [
    {
      "name": "Config resource 'file [/config-repo/product.yml]' via location 'file:/config-repo/' (document #1)",
      "source": {
        "spring.config.activate.on-profile": "docker",
        "server.port": 80,
        "spring.data.mongodb.host": "mongodb"
      }
    },
    {
      "name": "Config resource 'file [/config-repo/product.yml]' via location 'file:/config-repo/' (document #0)",
      "source": {
        "server.port": 7001,
        "server.error.include-message": "always",
        "spring.data.mongodb.host": "localhost",
        "spring.data.mongodb.port": 27017,
        "spring.data.mongodb.database": "product-db",
        "spring.cloud.function.definition": "messageProcessor",
        "spring.cloud.stream.default.contentType": "application/json",
        "spring.cloud.stream.bindings.messageProcessor-in-0.destination": "products",
        "spring.cloud.stream.bindings.messageProcessor-in-0.group": "productsGroup",
        "spring.cloud.stream.bindings.messageProcessor-in-0.consumer.maxAttempts": 3,
        "spring.cloud.stream.bindings.messageProcessor-in-0.consumer.backOffInitialInterval": 500,
        "spring.cloud.stream.bindings.messageProcessor-in-0.consumer.backOffMaxInterval": 1000,
        "spring.cloud.stream.bindings.messageProcessor-in-0.consumer.backOffMultiplier": 2,
        "spring.cloud.stream.rabbit.bindings.messageProcessor-in-0.consumer.autoBindDlq": true,
        "spring.cloud.stream.rabbit.bindings.messageProcessor-in-0.consumer.republishToDlq": true,
        "spring.cloud.stream.kafka.bindings.messageProcessor-in-0.consumer.enableDlq": true,
        "logging.level.root": "INFO",
        "logging.level.se.magnus": "DEBUG",
        "logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate": "DEBUG"
      }
    },
    {
      "name": "Config resource 'file [/config-repo/application.yml]' via location 'file:/config-repo/' (document #1)",
      "source": {
        "spring.config.activate.on-profile": "docker",
        "spring.rabbitmq.host": "rabbitmq",
        "spring.cloud.stream.kafka.binder.brokers": "kafka",
        "app.auth-server": "auth-server"
      }
    },
    {
      "name": "Config resource 'file [/config-repo/application.yml]' via location 'file:/config-repo/' (document #0)",
      "source": {
        "app.auth-server": "localhost",
        "spring.rabbitmq.host": "127.0.0.1",
        "spring.rabbitmq.port": 5672,
        "spring.rabbitmq.username": "guest",
        "spring.cloud.stream.kafka.binder.brokers": "127.0.0.1",
        "spring.cloud.stream.kafka.binder.defaultBrokerPort": 9092,
        "spring.cloud.stream.defaultBinder": "rabbit",
        "spring.zipkin.sender.type": "rabbit",
        "spring.sleuth.sampler.probability": 1,
        "management.endpoint.health.show-details": "ALWAYS",
        "management.endpoints.web.exposure.include": "*",
        "management.endpoint.health.probes.enabled": true,
        "management.endpoint.health.group.readiness.include": "rabbit, db, mongo",
        "server.shutdown": "graceful",
        "spring.lifecycle.timeout-per-shutdown-phase": "10s",
        "spring.rabbitmq.password": "guest"
      }
    }
  ]
}
```

**Comment by andreykirson** [comment]
@magnus-larsson hello. Thank you for your help.  
Response below:
![image](https://user-images.githubusercontent.com/32255911/143174757-b6b9d35d-1a25-4c03-86ef-2fc061cd8d17.png)

**Comment by magnus-larsson** [comment]
Hello again Andrey!

I think you misspelled `product` with `peoduct` :-)
But it doesn't matter since the `propertySources` - array should have picked up the file `/config-repo/application.yml` if the configuration was ok.

So I guess there is some problem with the config map that provides the config-server with its configuration.

Please run the following commands and provide me with its output and I will try to help you further!

Let's see what config-files that exists in the pod:

```
kubectl -n hands-on exec deploy/config-server -- ls /config-repo
```

Expect:

```
application.yml
auth-server.yml
gateway.yml
product-composite.yml
product.yml
recommendation.yml
review.yml
```

Look at the underlying config-map:

```
kubectl -n hands-on get cm config-server -o yaml
```

It should contain the content of the configuration files and start with:

```
apiVersion: v1
data:
  application.yml: |-
    app:
      auth-server: localhost
	  
...
```

Look at the config-repo in the source files of the Helm-chart for the config-server:

```
ls -l kubernetes/helm/components/config-server/config-repo
```

It should contain a soft (symbolic) link to the real config-repo, e.g.:

```
lrwxr-xr-x  1 magnus  staff  23 21 Nov 12:20 kubernetes/helm/components/config-server/config-repo -> ../../../../config-repo
```

Also verify that the config files exists in the config-repo:

```
ls -l config-repo
```

Expect:

```
-rw-r--r--  1 magnus  staff  1478 21 Nov 12:20 application.yml
-rw-r--r--  1 magnus  staff   229 21 Nov 12:20 auth-server.yml
-rw-r--r--  1 magnus  staff  1620 21 Nov 12:20 gateway.yml
-rw-r--r--  1 magnus  staff  5239 21 Nov 12:20 product-composite.yml
-rw-r--r--  1 magnus  staff  1554 21 Nov 12:20 product.yml
-rw-r--r--  1 magnus  staff  1575 21 Nov 12:20 recommendation.yml
-rw-r--r--  1 magnus  staff  1899 21 Nov 12:20 review.yml
```

Finally, lets see if there are any files changed compared to the source code of the book:

```
git status
```

It should say:

```
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

Also look at the git history:

```
git log
```

Expect ouput starting with:

```
commit b042770ca538bd656959bd2fad9c4e201d346e59 (HEAD -> main, origin/main, origin/HEAD)
Author: Magnus Larsson <magnus.larsson@callistaenterprise.se>
Date:   Fri Nov 19 10:42:10 2021 +0100

    Added explanation of how indices are created using Spring Data MongoDB

commit 569c9ed37282a6bbaa84b344ee40b0527a291701
Author: AniketS-cpu <54439994+AniketS-cpu@users.noreply.github.com>
Date:   Wed Jul 28 12:01:45 2021 +0530

    Update README.md

...
```

Regards,
Magnus.

**Comment by andreykirson** [comment]
@magnus-larsson hello.

I have added responses to all the commands that I call to run the project. 

![image](https://user-images.githubusercontent.com/32255911/143334791-8cde1603-8f37-4f5b-9cf2-8558cb26c4f5.png)
![image](https://user-images.githubusercontent.com/32255911/143334899-3b8c58d0-9793-41cd-bc94-865e7297efd5.png)
finally response:
![image](https://user-images.githubusercontent.com/32255911/143335452-61d5be0a-7bb0-4f3b-b8d8-a35e55728e04.png)
![image](https://user-images.githubusercontent.com/32255911/143336312-54e6e361-0e93-44a1-a6ad-5f94449a0ac8.png)
![image](https://user-images.githubusercontent.com/32255911/143337408-3bef63a3-a51e-4f6c-9f44-0405f0b0954c.png)
![image](https://user-images.githubusercontent.com/32255911/143337879-4cff305c-bbc6-42b3-950d-8ddf7dcbaeec.png)
![image](https://user-images.githubusercontent.com/32255911/143338438-023a62a6-c37b-4767-8adf-a5b40496cf2d.png)
![image](https://user-images.githubusercontent.com/32255911/143339604-0b5ccba6-86fe-4207-b430-c860f4d85c38.png)
![image](https://user-images.githubusercontent.com/32255911/143340652-7ea33d38-c9e0-442d-87c9-edf7e5ae5485.png)

**Comment by andreykirson** [comment]
When I call `kubectl -n hands-on exec deploy/config-server -- ls /config-repo`, nothing happened.

**Comment by magnus-larsson** [comment]
Great, thanks for your detailed output!

The issue can be seen on the last screendump where the soft link is broken.
The second last command should have reported a soft link (as seen in my comment above):

```
kubernetes/helm/components/config-server/config-repo -> ../../../../config-repo
```

I have no clue why the soft link is broken, but can you clone the git-repo to a temp folder to ensure that the soft link is retained in a newly cloned git-repo with the commands:

```
cd
mkdir issue6
cd issue6/
git clone https://github.com/PacktPublishing/Microservices-with-SpringBoot-and-Spring-Cloud-2E.git $BOOK_HOME
cd Microservices-with-Spring-Boot-and-Spring-Cloud-2E/Chapter16
ls -l kubernetes/helm/components/config-server/config-repo
ls kubernetes/helm/components/config-server/config-repo
```

The last two ls-commands should respond with something similar to:

```
$ ls -l kubernetes/helm/components/config-server/config-repo
lrwxrwxrwx 1 magnus magnus 23 Nov 25 09:12 kubernetes/helm/components/config-server/config-repo -> ../../../../config-repo

$ ls kubernetes/helm/components/config-server/config-repo
application.yml  auth-server.yml  gateway.yml  product-composite.yml  product.yml  recommendation.yml  review.yml
```

Let me know if this works for you, otherwise I have a major problem :-)

To fix the link in your code, please see page 475 in the book, where you can find the following command:

```
cd $BOOK_HOME/Chapter16/kubernetes/helm/components/config-server
ln -s ../../../../config-repo config-repo
```

After that, rerun the commands starting with the `helm dep up` - commands.

**Comment by andreykirson** [comment]
@magnus-larsson  hello. 

I forwarded one step ahead. 
In Windows OS with WSL by below command created a folder with files instead of a soft link, that's was a problem.  
`ln -s ../../../../config-repo config-repo`
 
All pods are running but the test still cannot be passed regardless of the parameters of USE_K8S true or false. The test ends with a "Give up!" message. How can I check where is a problem?
![image](https://user-images.githubusercontent.com/32255911/143725185-efd0bcc5-0324-487b-b3d3-04bae138bd35.png)

**Comment by magnus-larsson** [comment]
Great, good to have the microservices up and running!

The test-script `test-em-all.bash` waits for the microservices to be up and running using a `curl` command.
The curl command is written to the log output, on WSL2 it should look like:

```
curl -k https://localhost:30443/actuator/health
```

Can you try it out?

It should respond with a `json`-string starting with `{"status":"UP"`.

If **no** `json` is returned, ensure that the minikube cluster is created correctly, as described on page **434** for WSL2 on Windows.

If a `json`-string is returned but **not** starting with `{"status":"UP"`, then rerun the command with `jq` to format the output (to easier see what components causing the trouble):

```
curl -k https://localhost:30443/actuator/health | jq .
```

Look for components responding with `"status":"DOWN"` and update this issue with their log outputs using the `kubectl logs` command.

**Comment by andreykirson** [comment]
@magnus-larsson thank you for your helping. All test is passed. 

![image](https://user-images.githubusercontent.com/32255911/143764004-c6a765ff-0341-47ea-9e02-65bdc40614b6.png)
