### ISSUE TITLE
Chapter 06 - DuplicateKeyException Test for MongoDB

### ISSUE THREAD

**Issue by jpollard-github** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#7]
Not an issue, more to highlight for others if they run into the problem.

I couldn't get the duplicate() test for the product-service to pass for a while, until I looked at the source code for ProductServiceApplication in the code repo for Chapter06. Apparently, the @Indexed annotation isn't sufficient to actual create the unique index on productId, you need to use the IndexOperations ensureIndex functionality that's part of the Spring Data MongoDB library. So be sure to examine and copy the code [from Chapter 06 here](https://github.com/PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E/blob/main/Chapter06/microservices/product-service/src/main/java/se/magnus/microservices/core/product/ProductServiceApplication.java)

Again, not an issue with the code, but it was something that wasn't called out specifically in the book, and this might be new to folks who are new to Spring Data MongoDB and index creation.

So far, enjoying the book, thanks!

**Comment by magnus-larsson** [comment]
Hello Jason!

Well spotted, that should have been mentioned in the book!

I have added an *Errata* section in the [README.md](../blob/master/README.md#errata) file where I explain how index creation is handled for MongoDB.

**Comment by AndyLau223** [comment]
Thanks all. This saved me lots of time to find out the issue. thank you very much!
