### ISSUE TITLE
Chapter 17

### ISSUE THREAD

**Issue by andreykirson** [PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E#8]
@magnus-larsson hello.  I cloned your git and when in the folder chapter 17 and run the below command, it returns an error. 

`  helm template kubernetes / helm / components / product  --set envFromSecretRefs ="{rabbitmq-credentials, mongodb-credentials}"`

Error: found in Chart.yaml, but missing in charts/ directory: common

**Comment by magnus-larsson** [comment]
Hello Andrey!

I guess it means that it can't find the `common` library chart, introduced in Chapter 16, that the `product` chart depends on.

Can you try to first resolve the `product` chart's dependencies by running the command:

```
cd $BOOK_HOME/Chapter17
helm dep up kubernetes/helm/components/product
```

The template command should now work:

```
helm template kubernetes/helm/components/product --set envFromSecretRefs="{rabbitmq-credentials, mongodb-credentials}"
```

For further information, please see Chapter 16 for how the component charts, like the `product` chart, reuse common templates in the `common` library chart.

**Comment by magnus-larsson** [comment]
Hello Andrey!

Can we close this issue, or do you have any further questions related to this issue?

Regards,
Magnus.

**Comment by andreykirson** [comment]
@magnus-larsson.  
Thank you very much!  Just a quick note for windows users - the soft link does not work as expected they should create a folder with files instead of it.
